[theme]
base="dark"
primaryColor="#e74c3c"  # Un rojo elegante para destacar elementos clave
backgroundColor="#1b1b1b"  # Un gris oscuro profundo
secondaryBackgroundColor="#2c3e50"  # Un azul oscuro para áreas secundarias
textColor="#ecf0f1"  # Un blanco ligeramente grisáceo para el texto
font="sans serif"  # Fuente moderna y limpia